### ISSUE TITLE
Plugin Dados Abertos não iniciliazado

### ISSUE THREAD

**Issue by nettoclaudio** [thenets/DadosAbertosDocker#1]
Seguindo a instalação, de acordo com o arquivo `dadosabertos.sh`, em um container de CentOS 7.2. Foi necessário adicionar a extensão `dadosabertos` no `ckan.plugins` em `development.ini`. Sem isso o plugin não era carregada nunca.

**Comment by thenets** [comment]
Talvez vcs tenham adicionado algum plugin entre esses: "stats text_view image_view recline_view". Pois a linha de comando a seguir adiciona o "dadosabertos" aos plugins ativos no development.ini.

```
sed -i 's/stats text_view image_view recline_view/stats text_view image_view recline_view dadosabertos /g' /etc/ckan/default/development.ini
```

**Comment by nettoclaudio** [comment]
Exatamente isso. Obrigado, @thenets.
Acredito que o código abaixo seria mais conveniente(para evitar este tipo de problema).

```bash
sed -i 's/ckan.plugins =.*/& dadosabertos/g' /path/to/development.ini
sed -i 's/ckan.views.default_views =.*/& dadosabertos/g' /path/to/development.ini
```

**Comment by thenets** [comment]
Hmm, saída inteligente. Não tinha pensado nisso antes. Provavelmente vou usar como padrão para os outros plugins. Obrigad, cara.
